import oracledb
import sys

conn_params = {
    "user": "system",
    "password": "200806", 
    "dsn": "localhost:1521/xe"
}

def main():
    try:
        conn = oracledb.connect(**conn_params)
        cursor = conn.cursor()

        cursor.execute("""
            BEGIN
                EXECUTE IMMEDIATE 'CREATE TABLE tb_dimdim (
                    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    cliente VARCHAR2(100),
                    valor NUMBER(10, 2)
                )';
            EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
            END;
        """)
        conn.commit()

        while True:
            print("\n=== SISTEMA DIMDIM: CRUD ATIVO ===")
            print("1. Inserir | 2. Listar | 3. Atualizar | 4. Deletar | 5. Sair")
            op = input("Escolha: ")

            if op == '1':
                c = input("Nome do Cliente: ")
                v = float(input("Valor: "))
                cursor.execute("INSERT INTO tb_dimdim (cliente, valor) VALUES (:1, :2)", [c, v])
                conn.commit()
                print("✅ Sucesso!")
            elif op == '2':
                cursor.execute("SELECT * FROM tb_dimdim ORDER BY id")
                for r in cursor: print(f"ID: {r[0]} | Cliente: {r[1]} | R$: {r[2]}")
            elif op == '3':
                id_at = input("ID para atualizar: ")
                v_at = float(input("Novo Valor: "))
                cursor.execute("UPDATE tb_dimdim SET valor = :1 WHERE id = :2", [v_at, id_at])
                conn.commit()
            elif op == '4':
                id_del = input("ID para deletar: ")
                cursor.execute("DELETE FROM tb_dimdim WHERE id = :1", [id_del])
                conn.commit()
            elif op == '5':
                break
        
        cursor.close()
        conn.close()

    except Exception as e:
        print(f"❌ Erro: {e}")

if __name__ == "__main__":
    main()